version: "3.7"

services:

  mysql:
    image: mysql:8.0
    container_name: mysql-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: maa1234data
      MYSQL_DATABASE: mtandaodb
      MYSQL_USER: admin
      MYSQL_PASSWORD: 123456z

    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

  springboot:
    build: .
    container_name: mtandao-app
    restart: always
    ports:
      - "8081:8081"
    depends_on:
      - mysql
    environment:
      SPRING_DATASOURCE_URL: jdbc://mysql:3306/mtandaodb
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: 123456z

volumes:
  - mysql-data:
